imagga:
  api_key: ""
  api_secret: ""
mailgun:
  api_key: ""
  domain: ""
mqtt:
  queue: "ad-reg-queue"
  uri: ""
storage:
  mongodb:
    database: "ad-db"
    uri: ""
    enable: "false"
    local: "mongodb://127.0.0.1:27017/"
  s3:
    accessKeyID: ""
    secretAccessKey: ""
    region: "default"
    bucket: "ad-reg-bucket"
    endpoint: ""
